### ISSUE TITLE
Error with the mamPublish node

### ISSUE THREAD

**Issue by Deca** [Vruizvil/node-red-contrib-iota-mam#1]
Hi!
I'm trying to  use the mamPublish node but I get back this error in the node console:

```
failed to attach message:
 Error: Request Error: unexpected error while generating the balance diff
    at Object.requestError (C:\Users\Decagrog\.node-red\node_modules\node-red-contrib-iota-mam\node_modules\iota.lib.js\lib\errors\requestErrors.js:11:12)
    at makeRequest.prepareResult (C:\Users\Decagrog\.node-red\node_modules\node-red-contrib-iota-mam\node_modules\iota.lib.js\lib\utils\makeRequest.js:293:24)
    at exports.XMLHttpRequest.request.onreadystatechange (C:\Users\Decagrog\.node-red\node_modules\node-red-contrib-iota-mam\node_modules\iota.lib.js\lib\utils\makeRequest.js:71:25)
    at exports.XMLHttpRequest.dispatchEvent (C:\Users\Decagrog\.node-red\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:591:25)
    at setState (C:\Users\Decagrog\.node-red\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (C:\Users\Decagrog\.node-red\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:447:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Tested with different iota nodes, with or without POW enabled but all with IRI 1.6.1
I also noticed that the mam js library is way smaller than the original one in the iota repo, I thought your was too old so I simply  tried to replace it but this generate another error

`26 Mar 08:59:30 - [info] Waiting for missing types to be registered:
26 Mar 08:59:30 - [info]  - mamFetch`

**Comment by Vruizvil** [comment]
I have created mam publish and mam fetch in node-red-contrib-iota-lib, and works fine over mainnet and devnet. Please try the new version
